services:
  - type: web
    name: autopulse-app
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d1arremuk2gs7393oiqg-a/autopulse_db
      - key: SPRING_DATASOURCE_USERNAME
        value: autopulse_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 7qs06j1DCZUmeLT4EOtp3Z07reDiydZg
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /
    ports:
      - 8080

databases:
  - name: autopulse-db
    plan: free
