services:
  - type: web
    name: autopulse-app
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: autopulse-db
          property: jdbcConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: autopulse-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: autopulse-db
          property: password
    healthCheckPath: /

databases:
  - name: autopulse-db
    plan: free
